version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis-instance
    ports:
      - "6379:6379"
    networks:
      - shared-network

  caddy:
    build:
      context: ./
      dockerfile: Dockerfile.caddy
    container_name: caddy-instance
    ports:
      - "8080:8080"
    volumes:
      - ./Caddyfile:/Caddyfile:ro
    networks:
      - shared-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "3001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
